### ISSUE TITLE
Family Feud

### ISSUE THREAD

**Issue by Raghead** [Ragowit/psn100#11127]
**Game**
- https://psn100.net/game/13258-family-feud

**Information**
The online trophies are no longer unobtainable.
Ubisoft fixed the servers a while back.

- https://www.playstationtrophies.org/forum/topic/323329-trophy-boosting-thread-read-first-post/?do=findComment&comment=6566750
- https://forum.psnprofiles.com/topic/131013-online-not-working/?do=findComment&comment=2719763

**Comment by Ragowit** [comment]
Thanks! I'm very behind with updating the status of unobtainable trophies. Been a lot with life(tm). I will however fix this later tonight.

**Comment by Ragowit** [comment]
Going to close this issue as a duplicate of #10780, check that one for further info.
