### ISSUE TITLE
Tony Hawk's Pro Skater 5 [PS4]

### ISSUE THREAD

**Issue by TheYuriG** [Ragowit/psn100#11148]
**Game**
- [Tony Hawk Pro Skater 5 [PS4 version]](https://psn100.net/game/3698-tony-hawks-pro-skater-5)

**Trophies**
- https://psn100.net/trophy/105990-its-good-to-be-back
- https://psn100.net/trophy/106033-feedback-given
- https://psn100.net/trophy/106034-professional-judge
- https://psn100.net/trophy/106035-chief-judge

**Source**
- [PSNP Forums](https://forum.psnprofiles.com/topic/72378-is-this-obtainable/?do=findComment&comment=2389290)
- [Latest Achievers board](https://psnprofiles.com/trophy/3918-tony-hawks-pro-skater-5/44-feedback-given)
- https://psnp-plus.netlify.app/

**Comment by Ragowit** [comment]
Just checked PSNP+ and they list the PS3 version as affected as well.

https://psnprofiles.com/trophies/3918-tony-hawks-pro-skater-5
https://psnprofiles.com/trophies/4170-tony-hawks-pro-skater-5

**Comment by TheYuriG** [comment]
You are right, I've just checked the forums and there was nothing there about it, my bad.
It makes it less ironic to know that both versions are dead and not only the most recent hardware one.

**Comment by Ragowit** [comment]
Fixed in 6.67.796
