### ISSUE TITLE
Princess.Loot.Pixel.Again

### ISSUE THREAD

**Issue by Strategeru** [Ragowit/psn100#8419]
**Game**
- https://psn100.net/game/29184-princesslootpixelagain

**Trophy**
- https://psn100.net/trophy/899363-emerald
- https://psn100.net/trophy/899364-diamond
- https://psn100.net/trophy/899343-princesslootpixelagain-platinum

**Source**
- https://forum.psnprofiles.com/topic/118278-trophies-bugged-messaged-the-dev/

Currently glitched as of 30/11/2021
Game have same problem on Xbox, but achievements was patched on November 23rd 2021 with the 1.03 patch update.

**Comment by Ragowit** [comment]
Thanks! Those trophies are now tagged as unobtainable.

Fixed in 6.31.8
