### ISSUE TITLE
Five Nights at Freddy's: Security Breach

### ISSUE THREAD

**Issue by Ragowit** [Ragowit/psn100#8504]
**Games**
- https://psn100.net/game/29887-five-nights-at-freddys-security-breach
- https://psn100.net/game/29897-five-nights-at-freddys-security-breach

**Comment by Ragowit** [comment]
Fixed in 6.32.5

https://psn100.net/game/29910-five-nights-at-freddys-security-breach

**Comment by Joshua283638373y3837373373637** [comment]
Wtf is this

**Comment by Ragowit** [comment]
@Joshua283638373y3837373373637, can you please elaborate? What's your question?
